Upload assets and metadata
deus-labs/stargaze-tools pull request #4
Opened 2022-07-24 16:21 UTC by MightOfOaks

2022-07-27 09:26 UTC, findolor approved these changes

2022-07-27 09:26 UTC, findolor commented on config/network.ts
> +  chainId: 'stargaze',
Is this stargaze or elgafar-1?

2022-07-27 09:26 UTC, findolor commented on services/upload/nft-storage.ts
> +const NFT_STORAGE_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDJBODk5OGI4ZkE2YTM1NzMyYmMxQTRDQzNhOUU2M0Y2NUM3ZjA1RWIiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY1NTE5MTcwNDQ2Miw
Can we also get this as a user input?

2022-07-27 09:26 UTC, findolor commented on services/upload/pinata.ts
> +const pinataSecretKey = "9d6f42dc01eaab15f52eac8f36cc4f0ee4184944cb3cdbcda229d06ecf877ee7";
Can we also get these as user inputs?

2022-07-27 09:41 UTC, MightOfOaks commented on config/network.ts
> +  chainId: 'stargaze',
Having connection problems with chainId: 'elgafar-1'. 

'stargaze' seems to work.

2022-07-27 17:12 UTC, sascha1337 commented
my eslint was crying on each file, but didnt want to spam my name into the gitblame // log - lets see if thats fixed

2022-07-27 17:43 UTC, findolor commented
@sascha1337 we'll get those don't worry 👍

2022-07-28 06:31 UTC, findolor requested changes
Left some comments, also after selecting some images I cannot seem to get them to show up  unless I click on somewhere. They are rendered after that action so there might be a problem with the state

![Screen Recording 2022-07-28 at 09 30 09](https://user-images.githubusercontent.com/16416963/181436405-c8fffd48-5a8a-4b73-9941-ff9b82082297.gif)

2022-07-28 06:31 UTC, findolor commented on services/upload/pinata.ts
> +  if (fileType && fileType === 'metadata') {
Instead of using if else in here and duplicating code, let's assign this image prefix to a variable and use it that way. If we make use of the created type above;

```suggestion
data.append('file', file, `${fileType}/${file.name}`)
```

2022-07-28 06:31 UTC, findolor commented on services/upload/pinata.ts
> +const endpoint = 'https://api.pinata.cloud/pinning/pinFileToIPFS'
This can be moved to env variables

2022-07-28 06:31 UTC, findolor commented on services/upload/index.ts
> +export const serviceType = {
This can also be changed to 

```suggestion
export type UploadServiceType = 'nft-storage' | 'pinata'
```

2022-07-28 06:31 UTC, findolor commented on services/upload/pinata.ts
> +  fileType?: string,
We should enforce the file type in here always

```suggestion
type UploadFileType = 'metadata' | 'images'
fileType: UploadFIleType,
```

2022-07-28 13:38 UTC, merged